### PR TITLE
release prep

### PR DESCRIPTION
**Pull request by FredericBlum**
@LinguList Can we release this dataset?

### CODE REVIEW

**Review by chrzyki — CHANGES_REQUESTED** [review]
This still uses a local concept list but probably should be using `KochGrunberg-1914-821` from Concepticon.

**Comment by LinguList** [comment]
Don't we need concepticon concept sets first? WE have never ended up doing that. Or do we have this and it escaped my attention?

**Review by LinguList — APPROVED** [review]
How stupid from me, yes, I suggest to release it now :-)

**Comment by FredericBlum** [comment]
I have added the conceptlist-integration now. @chrzyki Could you quickly review if everything is alright with the integration?

**Review by chrzyki — CHANGES_REQUESTED** [review]
Cool, thank you! We typically have `idx_slugged_gloss` as ID for the parameter, where

```Python
idx = concept.id.split("-")[-1] + "_" + slug(concept.english)
```

(or similar), e.g. `1_sky`, `2_heaven` etc. The `Name` column is empty in the final `ParameterTable` and should be filled with the `Gloss` column from `KochGrunberg-1914-821`.

**Review by chrzyki — APPROVED** [review]
Thanks!

**Pull request merged**
